// Copyright (C) 2015-2020 the Gprovision Authors. All Rights Reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.
//
// SPDX-License-Identifier: MIT
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: log.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvtType int32

const (
	EvtType_LOG        EvtType = 0
	EvtType_MSG        EvtType = 1
	EvtType_SUCCESS    EvtType = 2
	EvtType_ERROR      EvtType = 3
	EvtType_SESS_START EvtType = 4
	// following are used in server app; likely not useful on wire.
	EvtType_PRINT     EvtType = 5
	EvtType_PRINT_ERR EvtType = 6
	EvtType_CODENAME  EvtType = 7
	EvtType_STATE     EvtType = 8
	EvtType_SETPW     EvtType = 9
)

// Enum value maps for EvtType.
var (
	EvtType_name = map[int32]string{
		0: "LOG",
		1: "MSG",
		2: "SUCCESS",
		3: "ERROR",
		4: "SESS_START",
		5: "PRINT",
		6: "PRINT_ERR",
		7: "CODENAME",
		8: "STATE",
		9: "SETPW",
	}
	EvtType_value = map[string]int32{
		"LOG":        0,
		"MSG":        1,
		"SUCCESS":    2,
		"ERROR":      3,
		"SESS_START": 4,
		"PRINT":      5,
		"PRINT_ERR":  6,
		"CODENAME":   7,
		"STATE":      8,
		"SETPW":      9,
	}
)

func (x EvtType) Enum() *EvtType {
	p := new(EvtType)
	*p = x
	return p
}

func (x EvtType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvtType) Descriptor() protoreflect.EnumDescriptor {
	return file_log_proto_enumTypes[0].Descriptor()
}

func (EvtType) Type() protoreflect.EnumType {
	return &file_log_proto_enumTypes[0]
}

func (x EvtType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvtType.Descriptor instead.
func (EvtType) EnumDescriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

type ProcessState int32

const (
	ProcessState_UNKNOWN        ProcessState = 0
	ProcessState_MFG_STARTED    ProcessState = 1
	ProcessState_MFG_SUCCEEDED  ProcessState = 2
	ProcessState_MFG_FAILED     ProcessState = 3
	ProcessState_FR_STARTED     ProcessState = 4
	ProcessState_FR_SUCCEEDED   ProcessState = 5
	ProcessState_FR_FAILED      ProcessState = 6
	ProcessState_INIT_STARTED   ProcessState = 7
	ProcessState_INIT_SUCCEEDED ProcessState = 8
	ProcessState_INIT_FAILED    ProcessState = 9
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "UNKNOWN",
		1: "MFG_STARTED",
		2: "MFG_SUCCEEDED",
		3: "MFG_FAILED",
		4: "FR_STARTED",
		5: "FR_SUCCEEDED",
		6: "FR_FAILED",
		7: "INIT_STARTED",
		8: "INIT_SUCCEEDED",
		9: "INIT_FAILED",
	}
	ProcessState_value = map[string]int32{
		"UNKNOWN":        0,
		"MFG_STARTED":    1,
		"MFG_SUCCEEDED":  2,
		"MFG_FAILED":     3,
		"FR_STARTED":     4,
		"FR_SUCCEEDED":   5,
		"FR_FAILED":      6,
		"INIT_STARTED":   7,
		"INIT_SUCCEEDED": 8,
		"INIT_FAILED":    9,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_log_proto_enumTypes[1].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_log_proto_enumTypes[1]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SN            string                 `protobuf:"bytes,1,opt,name=SN,proto3" json:"SN,omitempty"`
	EventType     EvtType                `protobuf:"varint,2,opt,name=EventType,proto3,enum=pb.EvtType" json:"EventType,omitempty"`
	Time          *Timestamp             `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetSN() string {
	if x != nil {
		return x.SN
	}
	return ""
}

func (x *LogEvent) GetEventType() EvtType {
	if x != nil {
		return x.EventType
	}
	return EvtType_LOG
}

func (x *LogEvent) GetTime() *Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// used for storage of multiple le's
type LogEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evt           []*LogEvent            `protobuf:"bytes,1,rep,name=Evt,proto3" json:"Evt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvents) Reset() {
	*x = LogEvents{}
	mi := &file_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvents) ProtoMessage() {}

func (x *LogEvents) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvents.ProtoReflect.Descriptor instead.
func (*LogEvents) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogEvents) GetEvt() []*LogEvent {
	if x != nil {
		return x.Evt
	}
	return nil
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TS            int64                  `protobuf:"varint,1,opt,name=TS,proto3" json:"TS,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{2}
}

func (x *Timestamp) GetTS() int64 {
	if x != nil {
		return x.TS
	}
	return 0
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     EvtType                `protobuf:"varint,1,opt,name=EventType,proto3,enum=pb.EvtType" json:"EventType,omitempty"` //only types that make sense here are ERROR and SUCCESS.
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{3}
}

func (x *GenericResponse) GetEventType() EvtType {
	if x != nil {
		return x.EventType
	}
	return EvtType_LOG
}

func (x *GenericResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type MACs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SN            string                 `protobuf:"bytes,1,opt,name=SN,proto3" json:"SN,omitempty"`
	MAC           []string               `protobuf:"bytes,2,rep,name=MAC,proto3" json:"MAC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MACs) Reset() {
	*x = MACs{}
	mi := &file_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MACs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MACs) ProtoMessage() {}

func (x *MACs) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MACs.ProtoReflect.Descriptor instead.
func (*MACs) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{4}
}

func (x *MACs) GetSN() string {
	if x != nil {
		return x.SN
	}
	return ""
}

func (x *MACs) GetMAC() []string {
	if x != nil {
		return x.MAC
	}
	return nil
}

type ProcessStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SN            string                 `protobuf:"bytes,1,opt,name=SN,proto3" json:"SN,omitempty"`
	State         ProcessState           `protobuf:"varint,2,opt,name=State,proto3,enum=pb.ProcessState" json:"State,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStage) Reset() {
	*x = ProcessStage{}
	mi := &file_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStage) ProtoMessage() {}

func (x *ProcessStage) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStage.ProtoReflect.Descriptor instead.
func (*ProcessStage) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessStage) GetSN() string {
	if x != nil {
		return x.SN
	}
	return ""
}

func (x *ProcessStage) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_UNKNOWN
}

type Codename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SN            string                 `protobuf:"bytes,1,opt,name=SN,proto3" json:"SN,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Codename) Reset() {
	*x = Codename{}
	mi := &file_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Codename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Codename) ProtoMessage() {}

func (x *Codename) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Codename.ProtoReflect.Descriptor instead.
func (*Codename) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{6}
}

func (x *Codename) GetSN() string {
	if x != nil {
		return x.SN
	}
	return ""
}

func (x *Codename) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SN            string                 `protobuf:"bytes,1,opt,name=SN,proto3" json:"SN,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Doctype       string                 `protobuf:"bytes,3,opt,name=Doctype,proto3" json:"Doctype,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{7}
}

func (x *Document) GetSN() string {
	if x != nil {
		return x.SN
	}
	return ""
}

func (x *Document) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Document) GetDoctype() string {
	if x != nil {
		return x.Doctype
	}
	return ""
}

func (x *Document) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{8}
}

func (x *Identifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OS            string                 `protobuf:"bytes,1,opt,name=OS,proto3" json:"OS,omitempty"`
	BIOS          string                 `protobuf:"bytes,2,opt,name=BIOS,proto3" json:"BIOS,omitempty"`
	IPMI          string                 `protobuf:"bytes,3,opt,name=IPMI,proto3" json:"IPMI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{9}
}

func (x *Credentials) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *Credentials) GetBIOS() string {
	if x != nil {
		return x.BIOS
	}
	return ""
}

func (x *Credentials) GetIPMI() string {
	if x != nil {
		return x.IPMI
	}
	return ""
}

var File_log_proto protoreflect.FileDescriptor

const file_log_proto_rawDesc = "" +
	"\n" +
	"\tlog.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x01\n" +
	"\bLogEvent\x12\x0e\n" +
	"\x02SN\x18\x01 \x01(\tR\x02SN\x12)\n" +
	"\tEventType\x18\x02 \x01(\x0e2\v.pb.EvtTypeR\tEventType\x12!\n" +
	"\x04Time\x18\x03 \x01(\v2\r.pb.TimestampR\x04Time\x12\x18\n" +
	"\aPayload\x18\x04 \x01(\tR\aPayload\"+\n" +
	"\tLogEvents\x12\x1e\n" +
	"\x03Evt\x18\x01 \x03(\v2\f.pb.LogEventR\x03Evt\"\x1b\n" +
	"\tTimestamp\x12\x0e\n" +
	"\x02TS\x18\x01 \x01(\x03R\x02TS\"T\n" +
	"\x0fGenericResponse\x12)\n" +
	"\tEventType\x18\x01 \x01(\x0e2\v.pb.EvtTypeR\tEventType\x12\x16\n" +
	"\x06ErrMsg\x18\x02 \x01(\tR\x06ErrMsg\"(\n" +
	"\x04MACs\x12\x0e\n" +
	"\x02SN\x18\x01 \x01(\tR\x02SN\x12\x10\n" +
	"\x03MAC\x18\x02 \x03(\tR\x03MAC\"F\n" +
	"\fProcessStage\x12\x0e\n" +
	"\x02SN\x18\x01 \x01(\tR\x02SN\x12&\n" +
	"\x05State\x18\x02 \x01(\x0e2\x10.pb.ProcessStateR\x05State\".\n" +
	"\bCodename\x12\x0e\n" +
	"\x02SN\x18\x01 \x01(\tR\x02SN\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"\\\n" +
	"\bDocument\x12\x0e\n" +
	"\x02SN\x18\x01 \x01(\tR\x02SN\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aDoctype\x18\x03 \x01(\tR\aDoctype\x12\x12\n" +
	"\x04Body\x18\x04 \x01(\fR\x04Body\"\x1c\n" +
	"\n" +
	"Identifier\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"E\n" +
	"\vCredentials\x12\x0e\n" +
	"\x02OS\x18\x01 \x01(\tR\x02OS\x12\x12\n" +
	"\x04BIOS\x18\x02 \x01(\tR\x04BIOS\x12\x12\n" +
	"\x04IPMI\x18\x03 \x01(\tR\x04IPMI*\x81\x01\n" +
	"\aEvtType\x12\a\n" +
	"\x03LOG\x10\x00\x12\a\n" +
	"\x03MSG\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0e\n" +
	"\n" +
	"SESS_START\x10\x04\x12\t\n" +
	"\x05PRINT\x10\x05\x12\r\n" +
	"\tPRINT_ERR\x10\x06\x12\f\n" +
	"\bCODENAME\x10\a\x12\t\n" +
	"\x05STATE\x10\b\x12\t\n" +
	"\x05SETPW\x10\t*\xb7\x01\n" +
	"\fProcessState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vMFG_STARTED\x10\x01\x12\x11\n" +
	"\rMFG_SUCCEEDED\x10\x02\x12\x0e\n" +
	"\n" +
	"MFG_FAILED\x10\x03\x12\x0e\n" +
	"\n" +
	"FR_STARTED\x10\x04\x12\x10\n" +
	"\fFR_SUCCEEDED\x10\x05\x12\r\n" +
	"\tFR_FAILED\x10\x06\x12\x10\n" +
	"\fINIT_STARTED\x10\a\x12\x12\n" +
	"\x0eINIT_SUCCEEDED\x10\b\x12\x0f\n" +
	"\vINIT_FAILED\x10\t26\n" +
	"\n" +
	"LogService\x12(\n" +
	"\x03Log\x12\f.pb.LogEvent\x1a\x13.pb.GenericResponse2\x89\x02\n" +
	"\fRecordKeeper\x12*\n" +
	"\tStoreMACs\x12\b.pb.MACs\x1a\x13.pb.GenericResponse\x12.\n" +
	"\rStoreIPMIMACs\x12\b.pb.MACs\x1a\x13.pb.GenericResponse\x124\n" +
	"\vReportState\x12\x10.pb.ProcessStage\x1a\x13.pb.GenericResponse\x123\n" +
	"\x0eReportCodename\x12\f.pb.Codename\x1a\x13.pb.GenericResponse\x122\n" +
	"\rStoreDocument\x12\f.pb.Document\x1a\x13.pb.GenericResponse2>\n" +
	"\n" +
	"Timekeeper\x120\n" +
	"\aGetTime\x12\x16.google.protobuf.Empty\x1a\r.pb.Timestamp2<\n" +
	"\aSecrets\x121\n" +
	"\x0eGetCredentials\x12\x0e.pb.Identifier\x1a\x0f.pb.CredentialsB0Z.github.com/mpictor/gprovision/pkg/oss/pblog/pbb\x06proto3"

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData []byte
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)))
	})
	return file_log_proto_rawDescData
}

var file_log_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_log_proto_goTypes = []any{
	(EvtType)(0),            // 0: pb.EvtType
	(ProcessState)(0),       // 1: pb.ProcessState
	(*LogEvent)(nil),        // 2: pb.LogEvent
	(*LogEvents)(nil),       // 3: pb.LogEvents
	(*Timestamp)(nil),       // 4: pb.Timestamp
	(*GenericResponse)(nil), // 5: pb.GenericResponse
	(*MACs)(nil),            // 6: pb.MACs
	(*ProcessStage)(nil),    // 7: pb.ProcessStage
	(*Codename)(nil),        // 8: pb.Codename
	(*Document)(nil),        // 9: pb.Document
	(*Identifier)(nil),      // 10: pb.Identifier
	(*Credentials)(nil),     // 11: pb.Credentials
	(*emptypb.Empty)(nil),   // 12: google.protobuf.Empty
}
var file_log_proto_depIdxs = []int32{
	0,  // 0: pb.LogEvent.EventType:type_name -> pb.EvtType
	4,  // 1: pb.LogEvent.Time:type_name -> pb.Timestamp
	2,  // 2: pb.LogEvents.Evt:type_name -> pb.LogEvent
	0,  // 3: pb.GenericResponse.EventType:type_name -> pb.EvtType
	1,  // 4: pb.ProcessStage.State:type_name -> pb.ProcessState
	2,  // 5: pb.LogService.Log:input_type -> pb.LogEvent
	6,  // 6: pb.RecordKeeper.StoreMACs:input_type -> pb.MACs
	6,  // 7: pb.RecordKeeper.StoreIPMIMACs:input_type -> pb.MACs
	7,  // 8: pb.RecordKeeper.ReportState:input_type -> pb.ProcessStage
	8,  // 9: pb.RecordKeeper.ReportCodename:input_type -> pb.Codename
	9,  // 10: pb.RecordKeeper.StoreDocument:input_type -> pb.Document
	12, // 11: pb.Timekeeper.GetTime:input_type -> google.protobuf.Empty
	10, // 12: pb.Secrets.GetCredentials:input_type -> pb.Identifier
	5,  // 13: pb.LogService.Log:output_type -> pb.GenericResponse
	5,  // 14: pb.RecordKeeper.StoreMACs:output_type -> pb.GenericResponse
	5,  // 15: pb.RecordKeeper.StoreIPMIMACs:output_type -> pb.GenericResponse
	5,  // 16: pb.RecordKeeper.ReportState:output_type -> pb.GenericResponse
	5,  // 17: pb.RecordKeeper.ReportCodename:output_type -> pb.GenericResponse
	5,  // 18: pb.RecordKeeper.StoreDocument:output_type -> pb.GenericResponse
	4,  // 19: pb.Timekeeper.GetTime:output_type -> pb.Timestamp
	11, // 20: pb.Secrets.GetCredentials:output_type -> pb.Credentials
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_proto_rawDesc), len(file_log_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		EnumInfos:         file_log_proto_enumTypes,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
