// Copyright (C) 2015-2020 the Gprovision Authors. All Rights Reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.
//
// SPDX-License-Identifier: MIT
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: log.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogService_Log_FullMethodName = "/pb.LogService/Log"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	// stream or no?
	Log(ctx context.Context, in *LogEvent, opts ...grpc.CallOption) (*GenericResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) Log(ctx context.Context, in *LogEvent, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, LogService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
type LogServiceServer interface {
	// stream or no?
	Log(context.Context, *LogEvent) (*GenericResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) Log(context.Context, *LogEvent) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call panics, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).Log(ctx, req.(*LogEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _LogService_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}

const (
	RecordKeeper_StoreMACs_FullMethodName      = "/pb.RecordKeeper/StoreMACs"
	RecordKeeper_StoreIPMIMACs_FullMethodName  = "/pb.RecordKeeper/StoreIPMIMACs"
	RecordKeeper_ReportState_FullMethodName    = "/pb.RecordKeeper/ReportState"
	RecordKeeper_ReportCodename_FullMethodName = "/pb.RecordKeeper/ReportCodename"
	RecordKeeper_StoreDocument_FullMethodName  = "/pb.RecordKeeper/StoreDocument"
)

// RecordKeeperClient is the client API for RecordKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// must implement imaging.RecordKeeper
type RecordKeeperClient interface {
	StoreMACs(ctx context.Context, in *MACs, opts ...grpc.CallOption) (*GenericResponse, error)
	StoreIPMIMACs(ctx context.Context, in *MACs, opts ...grpc.CallOption) (*GenericResponse, error)
	ReportState(ctx context.Context, in *ProcessStage, opts ...grpc.CallOption) (*GenericResponse, error)
	ReportCodename(ctx context.Context, in *Codename, opts ...grpc.CallOption) (*GenericResponse, error)
	StoreDocument(ctx context.Context, in *Document, opts ...grpc.CallOption) (*GenericResponse, error)
}

type recordKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordKeeperClient(cc grpc.ClientConnInterface) RecordKeeperClient {
	return &recordKeeperClient{cc}
}

func (c *recordKeeperClient) StoreMACs(ctx context.Context, in *MACs, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, RecordKeeper_StoreMACs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordKeeperClient) StoreIPMIMACs(ctx context.Context, in *MACs, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, RecordKeeper_StoreIPMIMACs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordKeeperClient) ReportState(ctx context.Context, in *ProcessStage, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, RecordKeeper_ReportState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordKeeperClient) ReportCodename(ctx context.Context, in *Codename, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, RecordKeeper_ReportCodename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordKeeperClient) StoreDocument(ctx context.Context, in *Document, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, RecordKeeper_StoreDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordKeeperServer is the server API for RecordKeeper service.
// All implementations must embed UnimplementedRecordKeeperServer
// for forward compatibility.
//
// must implement imaging.RecordKeeper
type RecordKeeperServer interface {
	StoreMACs(context.Context, *MACs) (*GenericResponse, error)
	StoreIPMIMACs(context.Context, *MACs) (*GenericResponse, error)
	ReportState(context.Context, *ProcessStage) (*GenericResponse, error)
	ReportCodename(context.Context, *Codename) (*GenericResponse, error)
	StoreDocument(context.Context, *Document) (*GenericResponse, error)
	mustEmbedUnimplementedRecordKeeperServer()
}

// UnimplementedRecordKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordKeeperServer struct{}

func (UnimplementedRecordKeeperServer) StoreMACs(context.Context, *MACs) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreMACs not implemented")
}
func (UnimplementedRecordKeeperServer) StoreIPMIMACs(context.Context, *MACs) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreIPMIMACs not implemented")
}
func (UnimplementedRecordKeeperServer) ReportState(context.Context, *ProcessStage) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportState not implemented")
}
func (UnimplementedRecordKeeperServer) ReportCodename(context.Context, *Codename) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCodename not implemented")
}
func (UnimplementedRecordKeeperServer) StoreDocument(context.Context, *Document) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreDocument not implemented")
}
func (UnimplementedRecordKeeperServer) mustEmbedUnimplementedRecordKeeperServer() {}
func (UnimplementedRecordKeeperServer) testEmbeddedByValue()                      {}

// UnsafeRecordKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordKeeperServer will
// result in compilation errors.
type UnsafeRecordKeeperServer interface {
	mustEmbedUnimplementedRecordKeeperServer()
}

func RegisterRecordKeeperServer(s grpc.ServiceRegistrar, srv RecordKeeperServer) {
	// If the following call panics, it indicates UnimplementedRecordKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordKeeper_ServiceDesc, srv)
}

func _RecordKeeper_StoreMACs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MACs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordKeeperServer).StoreMACs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordKeeper_StoreMACs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordKeeperServer).StoreMACs(ctx, req.(*MACs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordKeeper_StoreIPMIMACs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MACs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordKeeperServer).StoreIPMIMACs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordKeeper_StoreIPMIMACs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordKeeperServer).StoreIPMIMACs(ctx, req.(*MACs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordKeeper_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessStage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordKeeperServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordKeeper_ReportState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordKeeperServer).ReportState(ctx, req.(*ProcessStage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordKeeper_ReportCodename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Codename)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordKeeperServer).ReportCodename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordKeeper_ReportCodename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordKeeperServer).ReportCodename(ctx, req.(*Codename))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordKeeper_StoreDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Document)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordKeeperServer).StoreDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordKeeper_StoreDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordKeeperServer).StoreDocument(ctx, req.(*Document))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordKeeper_ServiceDesc is the grpc.ServiceDesc for RecordKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RecordKeeper",
	HandlerType: (*RecordKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreMACs",
			Handler:    _RecordKeeper_StoreMACs_Handler,
		},
		{
			MethodName: "StoreIPMIMACs",
			Handler:    _RecordKeeper_StoreIPMIMACs_Handler,
		},
		{
			MethodName: "ReportState",
			Handler:    _RecordKeeper_ReportState_Handler,
		},
		{
			MethodName: "ReportCodename",
			Handler:    _RecordKeeper_ReportCodename_Handler,
		},
		{
			MethodName: "StoreDocument",
			Handler:    _RecordKeeper_StoreDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}

const (
	Timekeeper_GetTime_FullMethodName = "/pb.Timekeeper/GetTime"
)

// TimekeeperClient is the client API for Timekeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimekeeperClient interface {
	GetTime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Timestamp, error)
}

type timekeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewTimekeeperClient(cc grpc.ClientConnInterface) TimekeeperClient {
	return &timekeeperClient{cc}
}

func (c *timekeeperClient) GetTime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Timestamp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Timestamp)
	err := c.cc.Invoke(ctx, Timekeeper_GetTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimekeeperServer is the server API for Timekeeper service.
// All implementations must embed UnimplementedTimekeeperServer
// for forward compatibility.
type TimekeeperServer interface {
	GetTime(context.Context, *emptypb.Empty) (*Timestamp, error)
	mustEmbedUnimplementedTimekeeperServer()
}

// UnimplementedTimekeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimekeeperServer struct{}

func (UnimplementedTimekeeperServer) GetTime(context.Context, *emptypb.Empty) (*Timestamp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedTimekeeperServer) mustEmbedUnimplementedTimekeeperServer() {}
func (UnimplementedTimekeeperServer) testEmbeddedByValue()                    {}

// UnsafeTimekeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimekeeperServer will
// result in compilation errors.
type UnsafeTimekeeperServer interface {
	mustEmbedUnimplementedTimekeeperServer()
}

func RegisterTimekeeperServer(s grpc.ServiceRegistrar, srv TimekeeperServer) {
	// If the following call panics, it indicates UnimplementedTimekeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Timekeeper_ServiceDesc, srv)
}

func _Timekeeper_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimekeeperServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timekeeper_GetTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimekeeperServer).GetTime(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Timekeeper_ServiceDesc is the grpc.ServiceDesc for Timekeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Timekeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Timekeeper",
	HandlerType: (*TimekeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTime",
			Handler:    _Timekeeper_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}

const (
	Secrets_GetCredentials_FullMethodName = "/pb.Secrets/GetCredentials"
)

// SecretsClient is the client API for Secrets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// for imaging.Stasher
type SecretsClient interface {
	GetCredentials(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Credentials, error)
}

type secretsClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsClient(cc grpc.ClientConnInterface) SecretsClient {
	return &secretsClient{cc}
}

func (c *secretsClient) GetCredentials(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Credentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Credentials)
	err := c.cc.Invoke(ctx, Secrets_GetCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsServer is the server API for Secrets service.
// All implementations must embed UnimplementedSecretsServer
// for forward compatibility.
//
// for imaging.Stasher
type SecretsServer interface {
	GetCredentials(context.Context, *Identifier) (*Credentials, error)
	mustEmbedUnimplementedSecretsServer()
}

// UnimplementedSecretsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsServer struct{}

func (UnimplementedSecretsServer) GetCredentials(context.Context, *Identifier) (*Credentials, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedSecretsServer) mustEmbedUnimplementedSecretsServer() {}
func (UnimplementedSecretsServer) testEmbeddedByValue()                 {}

// UnsafeSecretsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsServer will
// result in compilation errors.
type UnsafeSecretsServer interface {
	mustEmbedUnimplementedSecretsServer()
}

func RegisterSecretsServer(s grpc.ServiceRegistrar, srv SecretsServer) {
	// If the following call panics, it indicates UnimplementedSecretsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Secrets_ServiceDesc, srv)
}

func _Secrets_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Secrets_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServer).GetCredentials(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

// Secrets_ServiceDesc is the grpc.ServiceDesc for Secrets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Secrets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Secrets",
	HandlerType: (*SecretsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredentials",
			Handler:    _Secrets_GetCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
